"""Generate paper/references.bib from fetched metadata only (no hand-typed fields).

Sources (paper/bib_sources/):
  arxiv_meta.json   citation_* meta tags + comments/journal-ref of arXiv abs pages
  crossref_*.json   Crossref works API records
  aaai_srebro.json  extract of the AAAI proceedings page
A venue is written only when the arXiv comment or journal-ref field states it;
otherwise the entry is an arXiv preprint.
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.dirname(HERE)
SRC = os.path.join(PAPER, "bib_sources")

# key -> (arXiv id, venue string taken from the arXiv comment field or None)
ARXIV = {
    "stoica2024knots": ("2410.19735", None),
    "jin2023regmean": ("2212.09849", "International Conference on Learning Representations (ICLR)"),
    "nguyen2025regmeanpp": ("2508.03121", "Transactions on Machine Learning Research"),
    "he2026ctm": ("2606.03723", "International Conference on Machine Learning (ICML)"),
    "panariello2025core": ("2509.17786", "Conference on Neural Information Processing Systems (NeurIPS)"),
    "gargiulo2025tsv": ("2412.00081", "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)"),
    "marczak2025isoc": ("2502.04959", "International Conference on Machine Learning (ICML)"),
    "salami2024lorm": ("2410.17961", None),
    "li2026esm": ("2602.20208", "IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)"),
    "chen2024iteris": ("2411.15231", None),
    "amballa2026budget": ("2609.22237", None),
    "chen2024pareto": ("2408.12105", None),
    "li2024map": ("2406.07529", None),
    "samadi2018fairpca": ("1811.00103", None),
    "tantipongpipat2019multicriteria": ("1902.11281", "Conference on Neural Information Processing Systems (NeurIPS), preliminary version"),
    "song2024socially": ("2412.06063", "Conference on Neural Information Processing Systems (NeurIPS)"),
    "sagawa2019groupdro": ("1911.08731", None),
    "gao2018ratedistortion": ("1810.06401", None),
    "cao2026collapse": ("2603.09463", None),
    "hu2021lora": ("2106.09685", None),
    "ilharco2022taskarith": ("2212.04089", "International Conference on Learning Representations (ICLR)"),
    "yadav2023ties": ("2306.01708", "Conference on Neural Information Processing Systems (NeurIPS)"),
    "wang2025stablepca": ("2505.00940", None),
    "fries2026worstcase": ("2603.11304", None),
    "tang2024fusionbench": ("2406.03280", None),
    "wang2018glue": ("1804.07461", "International Conference on Learning Representations (ICLR)"),
    "chung2022flan": ("2210.11416", None),
    "warstadt2018cola": ("1805.12471", None),
    "bruelgabrielsson2024compress": ("2407.00066", None),
}
CROSSREF = {
    "eckart1936approximation": "crossref_10.1007_BF02288367.json",
    "izenman1975reduced": "crossref_10.1016_0047-259X_75_90042-1.json",
    "sion1958minimax": "crossref_10.2140_pjm.1958.8.171.json",
}


def tex_escape(s: str) -> str:
    s = s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")
    return s


def name_from_citation(a: str) -> str:
    # arXiv citation_author is "Family, Given"
    return a.strip()


def main() -> None:
    meta = json.load(open(os.path.join(SRC, "arxiv_meta.json")))
    out = ["% AUTO-GENERATED by paper/tools/make_bib.py from paper/bib_sources/. Do not edit by hand.", ""]
    for key, (aid, venue) in sorted(ARXIV.items()):
        m = meta[aid]
        year = m["date"][:4]
        authors = " and ".join(name_from_citation(a) for a in m["authors"])
        title = tex_escape(re.sub(r"\s+", " ", m["title"]))
        fields = [f"  title = {{{{{title}}}}}", f"  author = {{{tex_escape(authors)}}}",
                  f"  year = {{{year}}}", f"  eprint = {{{aid}}}", "  archivePrefix = {arXiv}"]
        if venue:
            fields.append(f"  note = {{arXiv:{aid}. {venue} (per the arXiv comment field)}}")
        else:
            fields.append(f"  note = {{arXiv preprint arXiv:{aid}}}")
        out.append(f"@misc{{{key},\n" + ",\n".join(fields) + "\n}\n")
    for key, fn in sorted(CROSSREF.items()):
        m = json.load(open(os.path.join(SRC, fn)))["message"]
        authors = " and ".join(f"{a.get('family')}, {a.get('given')}" for a in m["author"])
        fields = [f"  title = {{{{{tex_escape(m['title'][0])}}}}}", f"  author = {{{authors}}}",
                  f"  journal = {{{m['container-title'][0]}}}", f"  volume = {{{m.get('volume')}}}",
                  f"  number = {{{m.get('issue')}}}", f"  pages = {{{m.get('page').replace('-', '--')}}}",
                  f"  year = {{{m['issued']['date-parts'][0][0]}}}", f"  doi = {{{m['DOI']}}}"]
        out.append(f"@article{{{key},\n" + ",\n".join(fields) + "\n}\n")
    a = json.load(open(os.path.join(SRC, "aaai_srebro.json")))
    out.append("@inproceedings{srebro2003weighted,\n"
               f"  title = {{{{{a['title']}}}}},\n"
               "  author = {Srebro, Nathan and Jaakkola, Tommi},\n"
               f"  booktitle = {{{a['proceedings']}}},\n"
               "  year = {2003}\n}\n")
    with open(os.path.join(PAPER, "references.bib"), "w") as f:
        f.write("\n".join(out))
    print(f"wrote {len(ARXIV) + len(CROSSREF) + 1} entries")


if __name__ == "__main__":
    main()
